/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Consultas;
import logica.conexion;

/**
 *
 * @author Usuario
 */
public class FrmRegistro extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmRegistro
     */
    public FrmRegistro() {
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/files/1.png"));
        setIconImage(icon);
        this.setTitle("Registro");
        this.initComponents();
        InfMed();
      

    }
    private void Limpiar() {
        txtNumero.setText("");
        txtMedicamento.setText("");
        txtGramaje.setText("");
        txtCantidad.setText("");
        txtObservaciones.setText("");
    }

    void InfMed() {
        try {
            DefaultTableModel modelo;
            Consultas func = new Consultas();
            modelo = func.InformacionMedicamentos();

            TablaPrincipal.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }

    }

    void mostrar(String medicamento) {

        try {
            DefaultTableModel modelo;
            Consultas func = new Consultas();
            modelo = func.BuscarMedicamentos(medicamento);

            TablaPrincipal.setModel(modelo);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblMedicamento = new javax.swing.JLabel();
        txtMedicamento = new javax.swing.JTextField();
        txtGramaje = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        lblObservaciones = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblGramaje = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        jpalel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPrincipal = new javax.swing.JTable();
        btneliminarM = new javax.swing.JButton();
        lblburcarM = new javax.swing.JLabel();
        txtbuscarM = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Registrar Medicamneto"));

        lblNumero.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblNumero.setText("NUMERO:");

        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        lblMedicamento.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblMedicamento.setText("MEDICAMENTO:");

        txtMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicamentoActionPerformed(evt);
            }
        });

        txtGramaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGramajeActionPerformed(evt);
            }
        });

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        lblObservaciones.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblObservaciones.setText("OBSERVACIONES:");

        lblCantidad.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblCantidad.setText("CANTIDAD:");

        lblGramaje.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblGramaje.setText("GRAMAJE:");

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/guardar.png"))); // NOI18N
        btnguardar.setToolTipText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        BtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/lapiz.png"))); // NOI18N
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane2.setViewportView(txtObservaciones);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblObservaciones)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMedicamento)
                            .addComponent(lblNumero))
                        .addComponent(lblGramaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCantidad, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtMedicamento, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtGramaje, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNumero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGramaje, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGramaje, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnguardar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jpalel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Medicamentos"));

        TablaPrincipal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TablaPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NUMERO", "MEDICAMENTO", "GRAMAJE", "CANTIDAD", "OBSERVACIONES"
            }
        ));
        TablaPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaPrincipalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaPrincipal);

        btneliminarM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/eliminar.png"))); // NOI18N
        btneliminarM.setToolTipText("Eliminar Medicamentos");
        btneliminarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpalel1Layout = new javax.swing.GroupLayout(jpalel1);
        jpalel1.setLayout(jpalel1Layout);
        jpalel1Layout.setHorizontalGroup(
            jpalel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpalel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btneliminarM, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(439, 439, 439))
            .addGroup(jpalel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpalel1Layout.setVerticalGroup(
            jpalel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpalel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btneliminarM)
                .addGap(60, 60, 60))
        );

        lblburcarM.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblburcarM.setText("Buscar Medicamento:");

        txtbuscarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarMActionPerformed(evt);
            }
        });
        txtbuscarM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarMKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpalel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblburcarM)
                .addGap(18, 18, 18)
                .addComponent(txtbuscarM, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbuscarM, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblburcarM, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpalel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, Short.MAX_VALUE))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicamentoActionPerformed

    private void txtGramajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGramajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGramajeActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed

        if (txtNumero.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un numero para el medicamento");
            txtNumero.requestFocus();
        } else if (txtMedicamento.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un nombre para el nombre ");
            txtMedicamento.requestFocus();
        } else if (txtGramaje.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un gramaje para el medicamento");
            txtGramaje.requestFocus();
        } else if (txtCantidad.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar una cantidad para el medicamento");
            txtCantidad.requestFocus();
        } else if (txtObservaciones.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar una observacion para el empleado");
            txtObservaciones.requestFocus();
        } else {

            Consultas RegM = new Consultas();
            String numero = txtNumero.getText();
            String medicamento = txtMedicamento.getText();
            String gramaje = txtGramaje.getText();
            String cantidad = txtCantidad.getText();
            String observaciones = txtObservaciones.getText();
            RegM.RegistrarMedicamento(numero, medicamento, gramaje, cantidad, observaciones);

            InfMed();
            Limpiar();
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed

        Consultas cons = new Consultas();
        String Enumero = txtNumero.getText();
        String Emedicamento = txtMedicamento.getText();
        String Egramaje = txtGramaje.getText();
        String Ecantidad = txtCantidad.getText();
        String Eobservaciones = txtObservaciones.getText();

        cons.EdiatrMedicamento(Enumero, Emedicamento, Egramaje, Ecantidad, Eobservaciones);

        Limpiar();
        InfMed();
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void TablaPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaPrincipalMouseClicked
        try {
            int row = TablaPrincipal.getSelectedRow();
            String Vnumero = (TablaPrincipal.getModel().getValueAt(row, 0).toString());
            String Vmedicamento = (TablaPrincipal.getModel().getValueAt(row, 1).toString());
            String Vgramaje = (TablaPrincipal.getModel().getValueAt(row, 2).toString());
            String Vcantidad = (TablaPrincipal.getModel().getValueAt(row, 3).toString());
            String Vobservaciones = (TablaPrincipal.getModel().getValueAt(row, 4).toString());

            txtNumero.setText(Vnumero);
            txtMedicamento.setText(Vmedicamento);
            txtGramaje.setText(Vgramaje);
            txtCantidad.setText(Vcantidad);
            txtObservaciones.setText(Vobservaciones);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(rootPane, "Debes Completar Todos Los Campos");
        }
    }//GEN-LAST:event_TablaPrincipalMouseClicked

    private void btneliminarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarMActionPerformed

        if (!txtNumero.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Desea eliminar el medicamento " + txtMedicamento.getText() + " ? ", "Confrimar", 2);

            if (confirmacion == 0) {
                Consultas func = new Consultas();

                boolean h = func.EliminarMedicamento(txtNumero.getText());
                if (h == true) {
                    JOptionPane.showMessageDialog(rootPane, "Se ha Eliminado el Medicamento " + txtMedicamento.getText());
                } else {
                    JOptionPane.showMessageDialog(rootPane, "No se ha Podido eliminar el Medicamento");
                }
                Limpiar();
                InfMed();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debes seleccionar un Medicamento para eliminar");

        }

    }//GEN-LAST:event_btneliminarMActionPerformed

    private void txtbuscarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarMActionPerformed

    private void txtbuscarMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarMKeyReleased
        mostrar(txtbuscarM.getText());
    }//GEN-LAST:event_txtbuscarMKeyReleased
private final Connection connection = new conexion().Conectar();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEditar;
    private javax.swing.JTable TablaPrincipal;
    private javax.swing.JButton btneliminarM;
    private javax.swing.JButton btnguardar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpalel1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblGramaje;
    private javax.swing.JLabel lblMedicamento;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblObservaciones;
    private javax.swing.JLabel lblburcarM;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtGramaje;
    private javax.swing.JTextField txtMedicamento;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextArea txtObservaciones;
    private javax.swing.JTextField txtbuscarM;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelativeTo(Object object) {

    }

    private void setIconImage(Image icon) {

    }
}
