/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import logica.conexion;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *q
 * @author Brandon
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/files/1.png"));
        setIconImage(icon);
        this.setExtendedState(principal.MAXIMIZED_BOTH);
        this.setTitle("Menu Principal");
        initComponents();
        posicionarTexto();

    }

    private void posicionarTexto() {

        Dimension desktopSize = Escritorio.getSize();
        Dimension FrameSize = lbLogo.getSize();
        int x = (desktopSize.width - FrameSize.width) / 2;
        int y = (desktopSize.height - FrameSize.height) / 2;
        lbLogo.setLocation(x + 900, y + 500);
        lbLogo.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        lbLogo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        RegistrarMed = new javax.swing.JMenuItem();
        menu_ccontrasena = new javax.swing.JMenu();
        MnuCambiarContra = new javax.swing.JMenuItem();
        RegistrarUsuario = new javax.swing.JMenuItem();
        menu_reporte = new javax.swing.JMenu();
        Salir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/12.png"))); // NOI18N
        Escritorio.add(lbLogo);
        lbLogo.setBounds(660, 350, 710, 250);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/documento.png"))); // NOI18N
        jMenu1.setText("Medicamentos");
        jMenu1.setToolTipText("");
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jMenu1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        RegistrarMed.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        RegistrarMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/Registro.png"))); // NOI18N
        RegistrarMed.setText("Registrar");
        RegistrarMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarMedActionPerformed(evt);
            }
        });
        jMenu1.add(RegistrarMed);

        jMenuBar1.add(jMenu1);

        menu_ccontrasena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/usuario (1).png"))); // NOI18N
        menu_ccontrasena.setText("Opciones");
        menu_ccontrasena.setToolTipText("Cambiar Contraseña");
        menu_ccontrasena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_ccontrasena.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_ccontrasena.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        menu_ccontrasena.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menu_ccontrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_ccontrasenaMouseClicked(evt);
            }
        });
        menu_ccontrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                menu_ccontrasenaKeyPressed(evt);
            }
        });

        MnuCambiarContra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        MnuCambiarContra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/candado.png"))); // NOI18N
        MnuCambiarContra.setText("Cambiar Contrseña");
        MnuCambiarContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuCambiarContraActionPerformed(evt);
            }
        });
        menu_ccontrasena.add(MnuCambiarContra);

        RegistrarUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        RegistrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/agregar-usuario.png"))); // NOI18N
        RegistrarUsuario.setText("Registrar Usuario");
        RegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarUsuarioActionPerformed(evt);
            }
        });
        menu_ccontrasena.add(RegistrarUsuario);

        jMenuBar1.add(menu_ccontrasena);

        menu_reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/reportes.png"))); // NOI18N
        menu_reporte.setMnemonic('f');
        menu_reporte.setText("Imprimir");
        menu_reporte.setToolTipText("Reportes");
        menu_reporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_reporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_reporte.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        menu_reporte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menu_reporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_reporteMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_reporte);

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/salir123.png"))); // NOI18N
        Salir.setText("Salir");
        Salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Salir.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Salir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(Salir);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1266, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  private final Connection connection = new conexion().Conectar();
    private void menu_reporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_reporteMouseClicked
       
        Map p = new HashMap();
        JasperReport report;
        JasperPrint print;
        try {
            report = JasperCompileManager.compileReport(new File("").getAbsolutePath()
                    + "/src/Reporte/Rcensurados.jrxml");
            print = JasperFillManager.fillReport(report, p, connection);
            JasperViewer view = new JasperViewer(print, false);
            view.setTitle("Reporte General");
            view.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);

        }
    }//GEN-LAST:event_menu_reporteMouseClicked

    private void menu_ccontrasenaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_menu_ccontrasenaKeyPressed

    }//GEN-LAST:event_menu_ccontrasenaKeyPressed

    private void menu_ccontrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_ccontrasenaMouseClicked

    }//GEN-LAST:event_menu_ccontrasenaMouseClicked

    private void MnuCambiarContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuCambiarContraActionPerformed
        CambiarContraseña camb = new CambiarContraseña();
        Escritorio.add(camb);
        Dimension desktopSize = Escritorio.getSize();
        Dimension FrameSize = camb.getSize();
        camb.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        camb.toFront();
        camb.setVisible(true);
    }//GEN-LAST:event_MnuCambiarContraActionPerformed

    private void RegistrarMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarMedActionPerformed
        FrmRegistro Frm = new FrmRegistro();
        Escritorio.add(Frm);
        Dimension desktopSize = Escritorio.getSize();
        Dimension FrameSize = Frm.getSize();
        Frm.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        Frm.toFront();
        Frm.setVisible(true);
    }//GEN-LAST:event_RegistrarMedActionPerformed

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_SalirMouseClicked

    private void RegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarUsuarioActionPerformed
        AgregarUsuario frm = new AgregarUsuario();
        Escritorio.add(frm);
        Dimension desktopSize = Escritorio.getSize();
        Dimension FrameSize = frm.getSize();
        frm.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_RegistrarUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem MnuCambiarContra;
    private javax.swing.JMenuItem RegistrarMed;
    private javax.swing.JMenuItem RegistrarUsuario;
    private javax.swing.JMenu Salir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JMenu menu_ccontrasena;
    private javax.swing.JMenu menu_reporte;
    // End of variables declaration//GEN-END:variables
}
